{
 "title": "Visualization",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Podium",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT airline, delayed_flights FROM flights_db.airline_stats"
    }
   ]
  },
  {
   "title": "KPIs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT on_time_flights, delayed_flights, cancelled_flights \nFROM flights_db.airline_stats"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "SELECT original_airport, destination_airport, avg_delay\nFROM flights_db.route_stats\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Flight Distribution (AA)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT updated_at, on_time_flights, delayed_flights\nFROM flights_db.airline_stats\nWHERE airline = 'AA'\nALLOW FILTERING"
    }
   ]
  }
 ]
}